### ISSUE TITLE
Importing a namespace should include the "uses" for the namespace in the resulting namespace model object

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr-text-import#1]

**Comment by cmoesel** [comment]
In the current approach, we consider the "uses" statements as a convenience for authoring.  When the SHR tooling parses and builds the definitions, it uses the "uses" statements to correctly resolve identifiers without namespace -- but then stores the _fully resolved_ identifiers (with their namespaces).

We don't preserve the "uses" statements in the Namespace definitions because they are no longer needed since every identifier is fully resolved.  It is better for that resolution to happen as far upstream as possible rather than requiring every downstream tool to have to process the "uses" to resolve identifiers.

Given that all identifiers in the Namespace element definitions are already resolved, what would you wish to accomplish by having the "uses" statements preserved?

**Comment by gregquinn2001** [comment]
Yeah makes sense. I think the references should be fully qualified as you have it, but it still is useful to capture the uses statements during parsing into the models and let exporters decide how important that information is. The json hierarchy exporter would capture it as it makes displaying that information when viewing a namespace much easier.. Of course, the json exporter can figure it out by looking at all references from all data elements within each namespace if we decide not to include the uses information at the namespace level.

**Comment by markkramerus** [comment]
This probably should have been resolved based on Greg's last comment. Closing.
